[project]
name = 'arbiterium-core'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.arbiterium-core]
path = 'contracts/arbiterium-core.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = true
trusted_sender = true
trusted_caller = true
callee_filter = true

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
